services:
  backend:
    build: ./backend
    image: concord-backend
    ports:
      - "3001:3001"
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    build: ./frontend
    image: concord-frontend
    ports:
      - "8080:80"
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
