version: "3.8"

services:
  backend:
    image: concord-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    networks:
      - app-net

  frontend:
    image: concord-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: overlay
