services:
  backend:
    image: concord-backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
        mode: host
    networks:
      - app-net

  frontend:
    image: concord-frontend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - app-net

networks:
  app-net:
    external: true
