services:
  backend:
    image: concord-backend
    deploy:
      replicas: 1
    ports:
      - "3001:3001"
    networks:
      - app-net

  frontend:
    image: concord-frontend
    deploy:
      replicas: 1
    ports:
      - "8080:80"
    networks:
      - app-net

networks:
  app-net:
    external: true
