services:
  backend:
    image: concord-backend
    build: ./backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 3001
        published: 3001
    networks:
      - app-net

  frontend:
    image: concord-frontend
    build: ./frontend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 80
        published: 8080
    networks:
      - app-net

networks:
  app-net:
    driver: overlay
